# Generated by Django 5.0.6 on 2024-06-08 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(help_text='Age must be at least 15', validators=[django.core.validators.MinValueValidator(15)], verbose_name='Age'),
        ),
    ]
